import os
import numpy as np

def setup_run(x,time_pts,Nx,Ny,Nz,inner_path):
    num_CPUs = 1
    input_path = f'{inner_path}/Init_files'
    sim_path = f'{inner_path}/Run_main/Run_Sim'
    os.makedirs(sim_path,exist_ok=True)
    slurm_path = f'{inner_path}/Run_main/Slurm_Out'
    os.makedirs(slurm_path,exist_ok=True)
    out_path = f'{inner_path}/Out_files'
    os.makedirs(out_path,exist_ok=True)
    with open(f'{sim_path}/run_sim_{x}.sh','w') as fRun:
        fRun.write("#!/bin/sh\n")
        fRun.write("#SBATCH --mail-user=Saeed.Ahmad@nationwidechildrens.org\n")
        fRun.write("#SBATCH --mail-type=FAIL,REQUEUE\n")
        fRun.write("#SBATCH --job-name=20dis_inb\n")
        fRun.write("#SBATCH --time=13:00:00\n") # 7-0:00:00
        fRun.write("##SBATCH --partition=himem\n") # 7-0:00:00
        fRun.write("#SBATCH --cpus-per-task="+str(num_CPUs)+"\n")
        fRun.write("#SBATCH --ntasks=1\n")
        fRun.write(f"#SBATCH -o {slurm_path}/slurm.%j.out # STDOUT\n")
        fRun.write(f"#SBATCH -e {slurm_path}/slurm.%j.err # STDERR\n")
        fRun.write("\n")
        fRun.write("module load GCC/7.3.0-2.30 OpenMPI/3.1.1\n")
        fInName = f"{sim_path}/in."+str(x)
        fRun.write("mpirun -np 1 ./spk_redsky < "+fInName+"\n")      
          
        with open(fInName,'w') as fIn:
            fIn.write("# SPPARKS \n")
            fIn.write("\n")
            fIn.write(f"log      {out_path}/log.spparks_"+str(x)+"\n")
            fIn.write("seed     "+str(np.random.randint(0, 10000)+1)+"\n")
            fIn.write("\n")
            fIn.write("app_style    inb/diff/custom\n")
            fIn.write("\n")
            fIn.write("dimension    3\n")
            fIn.write("lattice      sc/6n 1\n")
            fIn.write("region       box block 0 "+str(Nx)+" 0 "+str(Ny)+" 0 "+str(Nz)+"\n")
            fIn.write("create_box   box\n")
            fIn.write("create_sites box\n")
            fIn.write("\n")
            fIn.write("region       global_bottom block 0 91 0 91 0 0\n")
            fIn.write("#region       sim_box block 0 10 0 10 0 0\n")
            fIn.write("#region       nkg2d block 5 5 5 5 0 0\n")
            fIn.write("#region       nkg2d_clus block 3 7 3 7 0 0\n")
            fIn.write("#region       kir_clus block 3 6 3 6 0 0\n")
            fIn.write("\n")
            old_path = input_path.replace('No_Kp_Inh', 'Kp_Both')
            fIn.write(f"read_sites       {old_path}/input_sppark.nkg2d_kir_ulbp3_hla.homogeneous_"+str(x)+"\n")
            fIn.write("\n")
            fIn.write("#set      i1 value 1 region global_bottom fraction 0.02\n")
            fIn.write("set      i2 value 1 region global_bottom\n")
            fIn.write("#set      i6 value 1 region nkg2d\n")
            fIn.write("#set      i9 value 3 region global_bottom\n")
            fIn.write("#set      i10 value 2 region global_bottom\n")
            fIn.write("#set      i16 value 1 region nkg2d_clus\n")
            fIn.write("#set      i17 value 1 region kir_clus\n")
            fIn.write("#set      i18 value 1 region global_bottom fraction 0.81\n")
            fIn.write("#set      i19 value 1 region kir_clus fraction 0.9\n")
            fIn.write("#set      i22 value 4 region global_bottom\n")
            fIn.write("#set      i27 value 1 region global_bottom\n")
            fIn.write("\n")
            fIn.write("sector   yes\n")
            fIn.write("solve_style  tree \n")
            fIn.write("\n")
            fIn.write("# species (note that in the C++ code indexing starts at 0 instead of 1)\n")
            fIn.write("add_species  l # i1 - unbound activating ligand\n")
            fIn.write("add_species  E # i2 - empty space (i.e. not a wall or free surface)\n")
            fIn.write("add_species  y # i3 - X cord \n")
            fIn.write("add_species  Y # i4 - Y cord \n")
            fIn.write("add_species  N # i5 - Voxel No.a\n")
            fIn.write("add_species  a # i6 - unbound activating receptors\n")
            fIn.write("add_species  A # i7 - bound activating receptors\n")
            fIn.write("add_species  p # i8 - phosphorylated bound activating receptors\n")
            fIn.write("add_species  k # i9 - SFK kinases\n")
            fIn.write("add_species  v # i10 -  unbounb Vav1s\n")
            fIn.write("add_species  V # 11 -  bounb Vav1s\n")
            fIn.write("add_species  P # i12 - phosphorylated Vav1 attached to AR_p\n")
            fIn.write("add_species  c # i13 - Lck+A complex \n")
            fIn.write("add_species  C # i14 - AR_p +vav+bounb SFK complex \n")
            fIn.write("add_species  f # i15 - free/unbound phosphorylated vav\n")
            fIn.write("add_species  W # i16 - AR cluster\n")
            fIn.write("add_species  w # i17 - IR cluster\n")
            fIn.write("add_species  L # i18 - unbound inhibiting ligands\n")
            fIn.write("add_species  i # i19 - unbound inhibiting receprors\n")
            fIn.write("add_species  I # i20 - bound inhibiting receprors\n")
            fIn.write("add_species  h # i21 - phosphorylated bound inhibiting receprors\n")
            fIn.write("add_species  s # i22 - unbound SHP\n")
            fIn.write("add_species  S # i23 - bound SHP\n")
            fIn.write("add_species  x # i24 - Lck+I complex\n")
            fIn.write("add_species  G # i25 - SHP attached to IR_p + p_Vav attached to AR_p\n")
            fIn.write("add_species  g # i26 - SHP attached to IR_p + free p_Vav\n")
            fIn.write("add_species  b # i27 - global sim box\n")
            fIn.write("add_species  B # i28 - boundary of sim_box (next to wall)\n")
            fIn.write("add_species  r # i29 - unbound vav'\n")
            fIn.write("add_species  R # i30 - bound vav'\n")
            fIn.write("add_species  D # i31 - ARp+bound vav'\n")
            fIn.write("add_species  Q # i32 - phos vav'+ARp\n")
            fIn.write("add_species  F # i33 - free phos vav'\n")
            fIn.write("add_species  Z # i34 - Shp+phos vav'+ARp\n")
            fIn.write("add_species  z # i35 - SHP+free phos vav'\n")
            fIn.write("add_species  j # i36 - NKG2D-SFK\n")
            fIn.write("add_species  H # i37 - pNKG2D-vav\n")
            fIn.write("add_species  t # i38 - pNKG2D\n")
            fIn.write("add_species  e # i39 - pNKG2D-vav-SFK\n")
            fIn.write("add_species  J # i40 - pNKG2D-pVav\n")
            fIn.write("add_species  K # i41 - pKIR-SHP-pNKG2D-pVav\n")
            fIn.write("add_species  M # i42 - pKIR-SHP\n")
            fIn.write("add_species  o # i43 - KIR-SFK\n")
            fIn.write("add_species  O # i44 - pKIR\n")
            fIn.write("add_species  T # i45 - pKIR-SHP-pNKG2D-vav\n")
            fIn.write("add_species  U # i46 - pKIR-HLA-SHP-pNKG2D-pvav\n")
            fIn.write("add_species  X # i47 - pKIR-SHP-pNKG2D-NKG2L-pvav\n")
            fIn.write("add_species  u # i48 - pKIR-SHP-pNKG2D-NKG2L-pvav\n")
            fIn.write("add_species  d # i49 - pKIR-SHP-pNKG2D-NKG2L-pvav\n")
            fIn.write("add_species  m # i50 - pKIR-SHP-pNKG2D-NKG2L-pvav\n")
            fIn.write("\n")
            fIn.write("# #AR + L_A\n")
            fIn.write("add_rxn      0 local l a nbr 12.3854688 local A nbr\n")
            fIn.write("add_rxn      1 local A nbr 0.023 local l a nbr\n")
            fIn.write("\n")
            fIn.write("# diffusion AR , SFK(s) vav(v)\n")
            fIn.write("\n")
            fIn.write("add_rxn      2 local l nbr E 6.25 local nbr l E\n")
            fIn.write("add_rxn      3 local a nbr E 6.25 local nbr a E\n")
            fIn.write("add_rxn      4 local k nbr E 6.25 local nbr k E\n")
            fIn.write("\n")
            fIn.write("# AR+kinase\n")
            fIn.write("add_rxn      5 local A k nbr 50.0 local c nbr\n")
            fIn.write("add_rxn      6 local c nbr 0.006 local A k nbr\n")
            fIn.write("\n")
            fIn.write("# phophorylation of  AR\n")
            fIn.write("add_rxn      7 local c nbr 2.1899058353952916 local p k nbr\n")
            fIn.write("\n")
            fIn.write("# AR_p + vav\n")
            fIn.write("add_rxn      8 local p v nbr 0.63421875 local V nbr\n")
            fIn.write("add_rxn      9 local V nbr 0.01 local p v nbr\n")
            fIn.write("\n")
            fIn.write("# ARp_vav + SFK\n")
            fIn.write("add_rxn      10 local V k nbr 50.0 local C nbr\n")
            fIn.write("add_rxn      11 local C nbr 0.028317078876353527 local V k nbr\n")
            fIn.write("\n")
            fIn.write("# Vav phosphoyntion attached to AP_p\n")
            fIn.write("add_rxn      12 local C nbr 0.7762549321707577 local P k nbr\n")
            fIn.write("\n")
            fIn.write("# dephospho\n")
            fIn.write("add_rxn      13 local P nbr 1.0 local V nbr\n")
            fIn.write("add_rxn      14 local p nbr 2.0 local A nbr\n")
            fIn.write("\n")
            fIn.write("# dissociation complex-phosphoVav to AR_p + phosp-vav\n")
            fIn.write("add_rxn      15 local P nbr 0.01 local p f nbr\n")
            fIn.write("add_rxn      16 local p f nbr 0.63421875 local P nbr\n")
            fIn.write("\n")
            fIn.write("# dephospho of free pvav\n")
            fIn.write("add_rxn      17 local f nbr 1.0 local v nbr\n")
            fIn.write("\n")
            fIn.write("# dissociation of Ar complexes \n")
            fIn.write("add_rxn      18 local c nbr 0.023 local l a k nbr\n")
            fIn.write("add_rxn      19 local p nbr 0.023 local l a nbr\n")
            fIn.write("add_rxn      20 local V nbr 0.023 local l a v nbr\n")
            fIn.write("add_rxn      21 local C nbr 0.023 local l a v k nbr\n")
            fIn.write("add_rxn      22 local P nbr 0.023 local l a v nbr\n")
            fIn.write("\n")
            fIn.write("#diffusion\n")
            fIn.write("add_rxn      23 local i nbr E 6.25 local nbr i E\n")
            fIn.write("\n")
            fIn.write("# #IR + L_I\n")
            fIn.write("add_rxn      24 local L i nbr 50.0 local I nbr\n")
            fIn.write("add_rxn      25 local I nbr 1.0 local L i nbr\n")
            fIn.write("\n")
            fIn.write("# AR+kinase\n")
            fIn.write("add_rxn      26 local I k nbr 50.0 local x nbr\n")
            fIn.write("add_rxn      27 local x nbr 0.006 local I k nbr\n")
            fIn.write("\n")
            fIn.write("# phophorylation of  IR\n")
            fIn.write("add_rxn      28 local x nbr 2.1899058353952916 local h k nbr\n")
            fIn.write("\n")
            fIn.write("# IR_p + Shp\n")
            fIn.write("add_rxn      29 local h s nbr 0.375 local S nbr\n")
            fIn.write("add_rxn      30 local S nbr 0.000509 local h s nbr\n")
            fIn.write("\n")
            fIn.write("# dephospho of IRp\n")
            fIn.write("add_rxn      31 local h nbr 2.0 local I nbr\n")
            fIn.write("\n")
            fIn.write("# (bound_SHP + IR_p complex) + (p_VAv + AR_p) complex\n")
            fIn.write("add_rxn      32 local S P nbr 50.0 local G nbr\n")
            fIn.write("add_rxn      33 local G nbr 0.01 local S P nbr\n")
            fIn.write("\n")
            fIn.write("# dephospho of dephosphorylation of pVAVcomplex due to bound-SHP\n")
            fIn.write("add_rxn      34 local G nbr 10.0 local S V nbr\n")
            fIn.write("\n")
            fIn.write("# (bound_SHP + IR_p complex) + (p_VAv + AR_p) complex\n")
            fIn.write("add_rxn      35 local S f nbr 6.3421875 local g nbr\n")
            fIn.write("add_rxn      36 local g nbr 0.01 local S f nbr\n")
            fIn.write("\n")
            fIn.write("# dephospho of dephosphorylation of pVAVcomplex due to bound-SHP\n")
            fIn.write("add_rxn      37 local g nbr 10.0 local S v nbr\n")
            fIn.write("\n")
            fIn.write("# dissociation of IR complexes \n")
            fIn.write("add_rxn      38 local x nbr 0.0 local L i k nbr\n")
            fIn.write("add_rxn      39 local h nbr 0.0 local L i nbr\n")
            fIn.write("add_rxn      40 local S nbr 0.0 local L i s nbr\n")
            fIn.write("add_rxn      41 local G nbr 0.0 local L i s P nbr\n")
            fIn.write("add_rxn      42 local G nbr 0.023 local l a v S nbr\n")
            fIn.write("add_rxn      43 local g nbr 0.0 local L i s v nbr\n")
            fIn.write("\n")
            fIn.write("#diffusion\n")
            fIn.write("add_rxn      44 local L nbr E 6.25 local nbr L E\n")
            fIn.write("\n")
            fIn.write("add_rxn      45 local l j nbr 0.0 local c nbr\n")
            fIn.write("add_rxn      46 local c nbr 0.0 local l j nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      47 local j nbr 0.0 local a k nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      48 local l H nbr 0.0 local V nbr\n")
            fIn.write("add_rxn      49 local V nbr 0.0 local l H nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      50 local H nbr 0.0 local t v nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      51 local l t nbr 0.0 local p nbr\n")
            fIn.write("add_rxn      52 local p nbr 0.0 local l t nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      53 local l e nbr 0.0 local C nbr\n")
            fIn.write("add_rxn      54 local C nbr 0.0 local l e nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      55 local e nbr 0.0 local H k nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      56 local e nbr 0.0 local J k nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      57 local l J nbr 0.0 local P nbr\n")
            fIn.write("add_rxn      58 local P nbr 0.0 local l J nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      59 local l U nbr 0.0 local G nbr\n")
            fIn.write("add_rxn      60 local G nbr 0.0 local l U nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      61 local l K nbr 0.0 local X nbr\n")
            fIn.write("add_rxn      62 local X nbr 0.0 local l K nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      63 local K nbr 0.0 local M J nbr\n")
            fIn.write("add_rxn      64 local J nbr 0.0 local t f nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      65 local L o nbr 50.0 local x nbr\n")
            fIn.write("add_rxn      66 local x nbr 1.0 local L o nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      67 local L O nbr 50.0 local h nbr\n")
            fIn.write("add_rxn      68 local h nbr 1.0 local L O nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      69 local L M nbr 50.0 local S nbr\n")
            fIn.write("add_rxn      70 local S nbr 1.0 local L M nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      71 local L X nbr 50.0 local G nbr\n")
            fIn.write("add_rxn      72 local G nbr 1.0 local L X nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      73 local L K nbr 50.0 local U nbr\n")
            fIn.write("add_rxn      74 local U nbr 1.0 local L K nbr\n")
            fIn.write("\n")
            fIn.write("add_rxn      75 local o nbr 0.006 local i k nbr\n")
            fIn.write("add_rxn      76 local M nbr 0.0005 local O s nbr\n")
            fIn.write("add_rxn      77 local o nbr 2.189 local O k nbr\n")
            fIn.write("add_rxn      78 local X nbr 10.0 local  M V nbr\n")
            fIn.write("add_rxn      79 local U nbr 10.0 local S H nbr\n")
            fIn.write("add_rxn      80 local K nbr 10.0 local M H nbr\n")
            fIn.write("add_rxn      81 local J nbr 1.0 local H nbr\n")
            fIn.write("add_rxn      82 local t nbr 2.0 local a nbr\n")
            fIn.write("add_rxn      83 local O nbr 2.0 local i nbr\n")
            fIn.write("\n")
            fIn.write("diag_style   propensity\n")
            fIn.write("diag_style   array i1 sum i2 sum i3 sum i4 sum i5 sum i6 sum i7 sum i8 sum i9 sum i10 sum i11 sum i12 sum i13 sum i14 sum i15 sum i16 sum i17 sum i18 sum i19 sum i20 sum i21 sum i22 sum i23 sum i24 sum i25 sum i26 sum i27 sum i28 sum i29 sum i30 sum i31 sum i32 sum i33 sum i34 sum i35 sum i36 sum i37 sum i38 sum i39 sum i40 sum i41 sum i42 sum i43 sum i44 sum i45 sum i46 sum i47 sum i48 sum i49 sum i50 sum\n")
            fIn.write("\n")
            fIn.write("stats           1.0\n")
            fIn.write(f"dump            1 sites 1.0 {out_path}/sites."+str(x)+".* id i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 i11 i12 i13 i14 i15 i16 i17 i18 i19 i20 i21 i22 i23 i24 i25 i26 i27 i28 i29 i30 i31 i32 i33 i34 i35 i36 i37 i38 i39 i40 i41 i42 i43 i44 i45 i46 i47 i48 i49 i50\n") 
            fIn.write("\n")
            fIn.write("run             "+str(time_pts)+"\n")
